//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BytonOpcService.DBOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_sys_statusRecord
    {
        public long id { get; set; }
        public string sys_ASRS_PLC { get; set; }
        public string sys_daemon_status { get; set; }
        public string sys_PLC_status { get; set; }
        public string ICE_1_status { get; set; }
        public string ICE_2_status { get; set; }
        public string ICE_3_status { get; set; }
        public string ICE_4_status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
