//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BytonOpcService.DBOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_stationReadRecord
    {
        public long id { get; set; }
        public string StationName { get; set; }
        public string BoxID { get; set; }
        public string F_TagReadStatus { get; set; }
        public string B_TagReadStatus { get; set; }
        public string TagReadResult { get; set; }
        public string StatusPrompt { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
