//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BytonOpcService.DBOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_productionRecord
    {
        public long id { get; set; }
        public string StationName { get; set; }
        public string TagID { get; set; }
        public string BoxID { get; set; }
        public string BoxType { get; set; }
        public string Distance { get; set; }
        public string TagPositon { get; set; }
        public string RFIDConnectionStatus { get; set; }
        public string R200ConnectionStatus { get; set; }
        public string ASRSReturnCode { get; set; }
        public string ASRSReadSignal { get; set; }
        public string RFID_ReturnCode { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
