//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BytonOpcService.DBOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_diagnosisRecord
    {
        public long id { get; set; }
        public string StationName { get; set; }
        public string RFID_VendorName { get; set; }
        public string RFID_ProductName { get; set; }
        public string RFID_SerialNumber { get; set; }
        public string RFID_HardwareVersion { get; set; }
        public string RFID_FirmwareVersion { get; set; }
        public string RFID_DeviceStatus { get; set; }
        public string RFID_Mode { get; set; }
        public string RFID_MemoryArea { get; set; }
        public string RFID_BytesNumber { get; set; }
        public string RFID_StartAddress { get; set; }
        public string RFID_TagType { get; set; }
        public string RFID_AutoStart { get; set; }
        public string R200_VendorName { get; set; }
        public string R200_ProductName { get; set; }
        public string R200_SerialNumber { get; set; }
        public string R200_HardwareVersion { get; set; }
        public string R200_FirmwareVersion { get; set; }
        public string R200_DeviceStatus { get; set; }
        public string R200_TemperatureIndicate { get; set; }
        public string R200_OperationHours { get; set; }
        public string ICE_OrderID { get; set; }
        public string ICE_SerialNumber { get; set; }
        public string ICE_HardwareVersion { get; set; }
        public string ICE_SoftwareVersion { get; set; }
        public string ICE_IMVersion { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
