//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BytonOpcService.DBOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_eventRecord
    {
        public long id { get; set; }
        public string EventName { get; set; }
        public string Excutor { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
