//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BytonOpcService.DBOperator
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_realTimeStationData
    {
        public long id { get; set; }
        public string StationName { get; set; }
        public string F_TagID { get; set; }
        public string F_BoxID { get; set; }
        public string F_BoxType { get; set; }
        public string F_R200Distance { get; set; }
        public string B_TagID { get; set; }
        public string B_BoxID { get; set; }
        public string B_BoxType { get; set; }
        public string B_R200Distance { get; set; }
        public string RFIDConnectionStatus { get; set; }
        public string R200ConnectionStatus { get; set; }
        public string ASRSReturnCode { get; set; }
        public string ASRSReadSignal { get; set; }
        public string RFID_ReturnCode { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RFID_ProductName { get; set; }
        public string RFID_SerialNumber { get; set; }
        public string RFID_HardwareVersion { get; set; }
        public string RFID_FirmwareVersion { get; set; }
        public string R200_ProductName { get; set; }
        public string R200_SerialNumber { get; set; }
        public string R200_HardwareVersion { get; set; }
        public string R200_FirmwareVersion { get; set; }
        public Nullable<System.DateTime> ModifiedDateForDiagnosis { get; set; }
    }
}
